code --uninstall-extension aaron-bond.better-comments
code --uninstall-extension anseki.vscode-color
code --uninstall-extension bradlc.vscode-tailwindcss
code --uninstall-extension calebporzio.simple-project-switcher
code --uninstall-extension christian-kohler.npm-intellisense
code --uninstall-extension christian-kohler.path-intellisense
code --uninstall-extension dbaeumer.vscode-eslint
code --uninstall-extension donjayamanne.githistory
code --uninstall-extension dsznajder.es7-react-js-snippets
code --uninstall-extension eamodio.gitlens
code --uninstall-extension EditorConfig.EditorConfig
code --uninstall-extension esbenp.prettier-vscode
code --uninstall-extension firefox-devtools.vscode-firefox-debug
code --uninstall-extension formulahendry.auto-close-tag
code --uninstall-extension formulahendry.auto-rename-tag
code --uninstall-extension GitHub.vscode-pull-request-github
code --uninstall-extension GraphQL.vscode-graphql
code --uninstall-extension GraphQL.vscode-graphql-syntax
code --uninstall-extension iocave.customize-ui
code --uninstall-extension iocave.monkey-patch
code --uninstall-extension mhutchie.git-graph
code --uninstall-extension mikestead.dotenv
code --uninstall-extension ms-azuretools.vscode-docker
code --uninstall-extension ms-edgedevtools.vscode-edge-devtools
code --uninstall-extension ms-python.python
code --uninstall-extension ms-vscode-remote.remote-containers
code --uninstall-extension ms-vscode-remote.remote-ssh
code --uninstall-extension ms-vscode-remote.remote-ssh-edit
code --uninstall-extension ms-vscode-remote.remote-wsl
code --uninstall-extension ms-vscode.cpptools
code --uninstall-extension ms-vscode.vscode-typescript-next
code --uninstall-extension ms-vsliveshare.vsliveshare
code --uninstall-extension naumovs.color-highlight
code --uninstall-extension redhat.vscode-xml
code --uninstall-extension sdras.night-owl
code --uninstall-extension steoates.autoimport
code --uninstall-extension styled-components.vscode-styled-components
code --uninstall-extension VisualStudioExptTeam.vscodeintellicode
code --uninstall-extension vscode-icons-team.vscode-icons
code --uninstall-extension vscodevim.vim
code --uninstall-extension yzhang.markdown-all-in-one
